server:
  port: 5555

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegramusers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

telegram-bot:
  botUserName: <login>
  botToken: <token>
  webHookPath: <hook>


